import Image from "next/image";
import { Box, Card, CardContent, CardHeader, Typography } from "@mui/material"
import { createTheme, ThemeProvider } from "@mui/material/styles";
import Head from "next/head";
import data from "../../data";
import styles from "../../styles/Projects.module.css"
import HomeButton from "../../components/HomeButton";
import { fontSize } from "@mui/system";

const theme = createTheme({
    palette: {
      primary: {
        main:'#f4f3ee'
      },
      secondary: {
        main: '#bcb8b1'
      }
    },
  })
  
  theme.typography.h1 = {
    fontWeight: '900',
    opacity: '0.7',
    fontFamily:'Bogart',
    [theme.breakpoints.up('xs')]: {
      fontSize: '3.4rem'
    },
    [theme.breakpoints.up('sm')]: {
      fontSize: '7rem',
    },
    [theme.breakpoints.up('md')]: {
      fontSize: '10rem',
    },
  
  };

  theme.typography.h3 = {
    fontFamily: 'Bogart',
    fontWeight: 500,
    fontSize: '1.7rem'
  }

export default function Projects() {
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles['main']}>
                <ThemeProvider theme={theme}>
                    <HomeButton></HomeButton>
           
                    <Box 
                        sx={{
                            width:"90%" ,
                            display: "flex",
                            flexDirection: "column",
                            alignItems:"center",
                            justifyContent: "space-between"
                        }}
                    >
                        <Typography variant="h1" color="primary"> Projects</Typography>
                        {
                            data.projects.map((project, index) => {
                                return(
                                    <Card 
                                        sx={{
                                            width:"65vw", 
                                            height:"70vh",
                                            marginBottom:'10vh',
                                            background: "linear-gradient(338.83deg,#f2e9e4 -3.41%,#ccb7ae,#f2e9e4 52.31%)",
                                            borderRadius: '10px'
                                        }} 
                                        // raised={true}
                                        key={index}
                                    >
                                        <CardHeader 
                                            title={project.name} 
                                            titleTypographyProps=
                                            {{
                                                variant:"h3",
                                                color:"secondary",
                                                textAlign:'right'

                                            }}
                                        >
                                        </CardHeader>
                                        <CardContent>
                                            <Box maxHeight="80%" display="flex" flexDirection='column' alignContent="center">
                                                <Box maxWidth="80%" display="block">
                                                    <Image 
                                                        src={project.image} 
                                                        placeholder="blur"
                                                        loading="lazy"
                                                    >
                                                    </Image>
                                                </Box>
                                            </Box>
                                        </CardContent>
                                    </Card>
                                )
                            })
                        }
                    </Box>
                </ThemeProvider>
            </main>
        </>
    )
}