import Image from "next/image";
import { Box, Card, CardContent, Typography } from "@mui/material"
import { createTheme, ThemeProvider } from "@mui/material/styles";
import Head from "next/head";
import data from "../../data";
import styles from "../../styles/Projects.module.css"

const theme = createTheme({
    palette: {
      primary: {
        main:'#f4f3ee'
      },
      secondary: {
        main: '#bcb8b1'
      }
    },
  })
  
  theme.typography.h1 = {
    fontWeight: '900',
    opacity: '0.7',
    fontFamily:'Bogart',
    [theme.breakpoints.up('xs')]: {
      fontSize: '3.4rem'
    },
    [theme.breakpoints.up('sm')]: {
      fontSize: '7rem',
    },
    [theme.breakpoints.up('md')]: {
      fontSize: '10rem',
    },
  
  };

  theme.typography.h4 = {
    fontFamily: 'Bogart',
    fontWeight: 500
  }

export default function Projects() {
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles['main']}>
                <ThemeProvider theme={theme}>
                    <Box 
                        sx={{
                            width:"90%" ,
                            display: "flex",
                            flexDirection: "column",
                            alignItems:"center",
                            justifyContent: "space-between"
                        }}
                    >
                        {
                            data.projects.map((project, index) => {
                                return(
                                    <Card 
                                        sx={{
                                            width:"65vw", 
                                            height:"70vh",
                                            marginBottom:'10vh',
                                            background: "linear-gradient(338.83deg,#f2e9e4 -3.41%,#ccb7ae,#f2e9e4 52.31%)",
                                        }} 
                                        // raised={true}
                                        key={index}
                                    >
                                        <CardContent>
                                            <Typography variant="h4" color="secondary" textAlign={'right'} fontWeight={700}>
                                                {project.name}
                                            </Typography>
                                            <Box maxWidth="80%" maxHeight="60%" display="block">
                                                <Image 
                                                    src={project.image} 
                                                    layout="responsive"
                                                    placeholder="blur"
                                                    loading="lazy"
                                                    sizes="50vw"
                                                >
                                                </Image>
                                            </Box>
                                        </CardContent>
                                    </Card>
                                )
                            })
                        }
                    </Box>
                </ThemeProvider>
            </main>
        </>
    )
}