import { Typography, Box, Grid } from "@mui/material";
import { useTheme } from '@mui/material/styles';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import Head from "next/head";
import Image from "next/image";
import HomeButton from "../../components/HomeButton";
import styles from "../../styles/About.module.css"

const theme = createTheme({
    palette: {
      primary: {
        main:'#f4f3ee'
      },
      secondary: {
        main: '#bcb8b1'
      }
    },
  })

  theme.typography.h1 = {
    fontWeight: '600',
    opacity: '0.7',
    [theme.breakpoints.up('xs')]: {
      fontSize: '3.2rem'
    },
    [theme.breakpoints.up('sm')]: {
      fontSize: '6.5rem',
    },
    [theme.breakpoints.up('md')]: {
      fontSize: '9rem',
    },

  };

const aboutObj = {
  aboutThisWebsite: "This current website was built with Next.js using React and Material UI.\n " +
  "The design concept was minimalism-focused like most of my projects, but was centered around this one animation I had in mind before fallng asleep one time.\n" +
  "I'm not a beginner in React animations, but most of my projects included linear, or predictical movements of elements in two degrees of freedom.\n" + 
  "My basic idea was that I was going to have some text that explodes in different directions on hover/press. \n" + 
  "As terrible and traumatizing as it was, the first thing I thought of to achieve this design was linear algebra. \n" + 
  "As for the effect of exploding letters, at the time I didn't expect to be writing a log-log function to model the behaviour I wanted. \n" +
  "Nevertheless, my effort in building a pure React hopefully paid off. Some extra things I didn't write about: (pseudo-random position generation & animation timing)\n"

}

export default function About() {

    return(
        <ThemeProvider theme={theme}>
            <Head>
              <title>About</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
              <HomeButton></HomeButton>
              <Box width="80%" height="100%">
                <Grid container spacing={4}>
                  <Grid container spacing={4} xs={12} justifyContent='center'>
                    <Grid container sm={5} xs={12} flexDirection='column' alignItems='center'>
                      <Grid item>
                        <Typography variant='h1' color="primary" maxHeight="fit-content" marginBottom="2rem" textAlign="left">About me</Typography>
                      </Grid>
                      <Grid item>
                        <Typography variant='h6' color="primary" marginBottom="2.5rem" textAlign="left"> Hi, I&apos;m <strong>Dylan</strong>—a <strong>Computer Engineering</strong> student at the <strong>University of Toronto</strong></Typography>
                      </Grid>
                      <Grid>
                        <Typography textAlign="center">{aboutObj.aboutThisWebsite}</Typography>
                      </Grid>
                    </Grid>
                    <Grid item sm={4.5} xs={12} textAlign="right">
                      <Image src='/me.jpeg' layout="responsive" height="332.5" width="250" style={{height:'auto', width:'10vw'}}></Image>
                    </Grid>
                  </Grid>
                </Grid>
              </Box>
            </main>
        </ThemeProvider>
    )
}