import { Typography, Box, Grid } from "@mui/material";
import { useTheme } from '@mui/material/styles';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import { fontFamily } from "@mui/system";
import Head from "next/head";
import Image from "next/image";
import me from "../../public/me.jpeg"
import HomeButton from "../../components/HomeButton";
import styles from "../../styles/About.module.css"

const theme = createTheme({
    palette: {
      primary: {
        main:'#f4f3ee'
      },
      secondary: {
        main: '#bcb8b1'
      }
    },
  })

  theme.typography.h1 = {
    fontWeight: '600',
    opacity: '0.7',
    fontFamily: 'Bogart',
    [theme.breakpoints.up('xs')]: {
      fontSize: '3.2rem',
      textAlign: 'center'
    },
    [theme.breakpoints.up('sm')]: {
      fontSize: '4.5rem',
      textAlign: 'left'

    },
    [theme.breakpoints.up('md')]: {
      fontSize: '7rem',
      textAlign: 'left'
    },

  };

  theme.typography.h6 = {
    fontFamily: 'Bogart',
    fontWeight: 400,
    fontSize: '1.5rem',
  }

const aboutObj = {
  aboutThisWebsite: "This current website was built with Next.js using React and Material UI.\n " +
  "The design concept was minimalism-focused like most of my projects, but was centered around this one animation I had in mind before fallng asleep one time.\n" +
  "I'm not a beginner in React animations, but most of my projects included linear, or predictical movements of elements in two degrees of freedom.\n" + 
  "My basic idea was that I was going to have some text that explodes in different directions on hover/press. \n" + 
  "As terrible and traumatizing as it was, the first thing I thought of to achieve this design was linear algebra. \n" + 
  "As for the effect of exploding letters, at the time I didn't expect to be writing a log-log function to model the behaviour I wanted. \n" +
  "Nevertheless, my effort in building a pure React animation hopefully paid off. Some extra things I didn't write about: (pseudo-random position generation & animation timing)\n",
  aboutMe: "I'm a fullstack developer with experience developing with Javascript, Python, React, and Node." +
  "I enjoy spending time learning how to use new technology (this website was create with Next.js!) and playing music in my spare time!"

}

export default function About() {

    return(
        <ThemeProvider theme={theme}>
            <Head>
              <title>About</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
              <HomeButton></HomeButton>
              <Box width="80%" height="100%">
                <Grid container justifyContent="center">
                  <Grid container xs={12} justifyContent='center'>
                    <Grid container sm={5} xs={12} flexDirection='column'>
                      <Grid item>
                        <Typography variant='h1' color="primary" maxHeight="fit-content">About me</Typography>
                      </Grid>
                      <Grid item>
                        <Typography variant='h6' color="secondary" marginBottom="2.5rem" textAlign={{xs:'center', sm:'left'}}> Hi, I&apos;m <strong>Dylan</strong>—a <strong>Computer Engineering</strong> student at the <strong>University of Toronto</strong></Typography>
                      </Grid>
                    </Grid>
                    <Grid item sm={5} xs={12} textAlign="right">
                      <Image src={me} layout="intrinsic" height="532" width="400"></Image>
                    </Grid>
                  </Grid>
                  <Grid container xs={12} justifyContent="center">
                    <Grid item xs={9.5}>
                      {/* <Typography textAlign="center">{aboutObj.aboutThisWebsite}</Typography> */}
                      <Typography textAlign="left" color="secondary">{aboutObj.aboutMe}</Typography>
                    </Grid>

                  </Grid>
                </Grid>
              </Box>
            </main>
        </ThemeProvider>
    )
}